### ISSUE TITLE
Feature "One select for all fields on a page" doesnt work

### ISSUE THREAD

**Issue by bendadaniel** [outl1ne/nova-translatable#76]
Hello, 
feature "One select for all fields on a page", doesnt work and throw js error on select change.

**Resource:**
```
LocaleSelect::make(),                 
Text::make('Title', 'title')->translatable(),
Textarea::make('Perex', 'perex')->translatable(),
```

**Setting:**
```
'display_type' => 'none', 
```

**On language select box change js thow this error:**
```
runtime-core.esm-bundler.js:226 
TypeError: Cannot read properties of undefined (reading 'value')
    at onChange.r.<computed>.r.<computed> (nova-translatable-select-field:2:176462)
    at en (runtime-core.esm-bundler.js:155:22)
    at tn (runtime-core.esm-bundler.js:164:21)
    at Ln (runtime-core.esm-bundler.js:718:9)
    at Proxy.handleChange (SelectControl.vue:96:12)
    at onChange.t.<computed>.t.<computed> (SelectControl.vue:6:16)
    at en (runtime-core.esm-bundler.js:155:22)
    at tn (runtime-core.esm-bundler.js:164:21)
    at HTMLSelectElement.n (runtime-dom.esm-bundler.js:366:13)
```

Has anyone same problem? Thank you

**Comment by Tarpsvo** [comment]
Heya! It should work now in version 2.0.1. Good luck!
